FROM python:3.8

# Initialize
RUN mkdir -p /data/rrsm
WORKDIR /data/rrsm
COPY requirements.txt /data/rrsm/

# Install deps
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Prepare
COPY . /data/rrsm/
