FROM debian

# Initialize
RUN mkdir -p /data/rrsm
WORKDIR /data/rrsm
COPY requirements.txt /data/rrsm/

# Setup
RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip gettext libpng-dev libxml2-dev libxslt-dev lib32z1-dev
RUN pip3 install --upgrade pip
# Install the numpy separate from the bulk requirements
# install because otherwise ObsPy installation fails
RUN pip3 install numpy==1.14.2
RUN pip3 install -r requirements.txt

# Prepare
COPY . /data/rrsm/
RUN python3 manage.py collectstatic