# Generated by Django 2.0.2 on 2018-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=256)),
                ('date_start', models.DateField(blank=True, default='')),
                ('date_end', models.DateField(blank=True, default='')),
                ('magnitude_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('network_code', models.CharField(blank=True, max_length=256)),
                ('station_code', models.CharField(blank=True, max_length=256)),
                ('level', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FdsnNode',
            fields=[
                ('code', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('url_event', models.CharField(blank=True, default='', max_length=1024)),
                ('url_motion', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('category', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
