version: '2'
services:
  rrsmweb:
    restart: always
    build: ./rrsm/
    ports:
      - "8000:8000"
    networks:
      - rrsm_net
    command: gunicorn rrsm.wsgi:application --timeout 300 -w 2 -b :8000

networks:
  rrsm_net: